name: Create Release
on:
  workflow_run:
      workflows: ["Publish to PyPI"]
      types:
        - completed
      branches:
        - v0.1.4
jobs:
    build:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: v0.1.4
            release_name: v0.1.4
            body: |
              Testing auto deployment to pypi and git.
            draft: false
            prerelease: true