# Build the package and publish it to PyPI after tests pass.
name: Publish to PyPI
on:
  workflow_run:
    workflows: ["run_tests"]
    types:
      - completed
    branches:
      - v0.1.5

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: v0.1.5
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Build package
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.DPLPY_PYPI }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.1.5
          release_name: v0.1.5
          body: |
            Testing auto deployment to pypi and git.
          draft: false
          prerelease: true
